POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Khadija M Junaid",
    "number": "07916765796"
}

### 
POST https://contact-book.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "John Doe"
}

### 
POST https://contact-book.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "number": "2988291"
}

### 
POST https://contact-book.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": "2423234"
}